# Generated by Django 5.0.8 on 2024-08-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_website_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="website",
            name="status",
            field=models.CharField(
                choices=[
                    ("R", "Reviewed"),
                    ("A", "Accepted"),
                    ("N", "Not Reviewed"),
                    ("E", "Error"),
                ],
                max_length=1,
            ),
        ),
    ]
